const saude_mental = [
    {
        titulo: 'Ansiedade e Depressão na Adolescência',
        texto: 'A adolescência é um período de transformações biológicas, psicológicas e sociais, no qual o jovem precisa se redefinir com relação a si mesmo e ao meio em que está inserido. Além disso, é marcada por eventos significativos, como a escolha profissional e entrada no mundo adulto, que podem gerar alta reatividade emocional e provocar conflitos familiares. Assim, é comum nessa fase da vida a inquietação e a sensação de estranheza a si próprio, seja por sua nova forma de ver o mundo, por sua sexualidade ou por seu corpo. Isso pode gerar uma grande vulnerabilidade emocional, quadro no qual os sintomas depressivos e de ansiedade não são incomuns (BRITO, 2011; GROLLI; WAGNER; DALBOSCO, 2017). Nesse contexto, o sofrimento psíquico mostra-se extremamente prejudicial aos estudantes, haja visto que este pode levar ao mau desempenho acadêmico e em relações interpessoais e ao consumo de álcool e drogas (BRITO, 2011). Por isso, é importante investigar as causas desse fenômeno e promover ações de prevenção relacionadas à temática da saúde mental, a fim de auxiliar os estudantes (GROLLI; WAGNER; DALBOSCO, 2017). Para saber mais sobre as manifestações ansiosas e depressivas na adolescência, acesse os links abaixo:',
        links: ['https://rpmgf.pt/ojs/index.php/rpmgf/article/view/10842', 'https://dialnet.unirioja.es/servlet/articulo?codigo=6185316', 'https://youtu.be/Tv0gJTBmVuc']
    },
    {
        titulo: 'Suicídio',
        texto: '“A cada 40 segundos, uma pessoa comete suicídio no mundo, totalizando mais de 800 mil mortes por ano. Os dados constam em documento divulgado em 2014 pela Organização Mundial de Saúde (OMS). Segundo o relatório, o Brasil  é o oitavo país com mais casos:  cerca de 12 mil pessoas se matam, anualmente. No DF, uma das unidades da federação com índice mais baixo de suicídio, segundo a OMS, uma média de 130 pessoas tiram a própria vida por ano. [...] O suicídio é considerado um problema de saúde pública pela OMS desde 2006. Ainda segundo a organização, é a segunda maior causa de mortes entre pessoas de 15 a 29 anos de idade. Porém, 90% dos casos podem ser evitados. Dados da OMS indicam que o suicídio geralmente aparece associado a doenças mentais – sendo que a mais comum, atualmente, é a depressão, responsável por 30% dos casos relatados em todo o mundo. Estima-se que uma em cada quatro pessoas sofrerá de depressão ao longo da vida. O alcoolismo responde por 18% dos casos de suicídio, a esquizofrenia por 14% e os transtornos de personalidade por 13%. Os casos restantes são relacionados a outros diagnósticos psiquiátricos.” Você também pode complementar sua leitura acessando os seguintes links:',
        links: ['https://www.saude.df.gov.br/web/guest/w/segundo-oms-90-dos-casos-de-suicidio-poderiam-ser-evitados', 'https://www.saude.ba.gov.br/2020/09/10/oms-alerta-suicidio-e-a-3a-causa-de-morte-de-jovens-brasileiros-entre-15-e-29-anos/', 'https://brasil.un.org/pt-br/201139-covid-19-crises-de-ansiedade-afetaram-63-dos-jovens-no-%C3%BAltimo-semestre#', 'https://www.cnnbrasil.com.br/saude/depressao-e-ansiedade-entre-jovens-dobraram-durante-a-pandemia-revela-pesquisa/', 'https://g1.globo.com/jornal-nacional/noticia/2022/05/30/pesquisa-revela-o-impacto-emocional-da-pandemia-3-em-cada-10-jovens-entrevistados-relataram-sintomas-de-ansiedade.ghtml']
    },
    {
        titulo: 'Como lidar com a ansiedade?',
        texto: 'Além de entender o que é a ansiedade, é importante entender algumas formas de lidar com as crises causadas por ela; para isso, você pode acessar os links abaixo:',
        links: ['https://summitsaude.estadao.com.br/saude-humanizada/7-tecnicas-para-controlar-a-ansiedade/', 'https://youtu.be/8YG8HABY25w', 'https://www.youtube.com/watch?v=UJS6C77DV9c', 'https://www.napratica.org.br/mindfulness-como-aplicar/', 'https://iptc.net.br/triade-cognitiva/']
    },
    {
        titulo: 'Transtornos Depressivos',
        texto: 'Existem alguns tipos de transtornos depressivos, dentre os quais estão: Transtorno depressivo de desregulação do humor;  Transtorno depressivo maior; Transtorno depressivo persistente (distimia); Transtorno disfórico pré-menstrual; Transtorno depressivo induzido por substância/medicamento; Transtorno depressivo não especificado. O transtorno depressivo maior é o mais conhecido por ser considerado um quadro clássico desse grupo de transtornos. Esse tipo de transtorno comumente se manifesta por episódios de duração de, no mínimo, duas semanas e é marcado  por alterações no afeto, na cognição e em funções neurovegetativas.  Quando os episódios são associados ao luto – o luto por si só não costuma provocar quadros depressivos – os prejuízos tendem a ser maiores, afetando o funcionamento social, profissional e de outras áreas. Muitas vezes altos níveis de ansiedade são associados ao aumento do risco de suicídio e a maior duração do transtorno pode ocasionar a maior probabilidade de pouca resposta do tratamento. Os transtornos ansiosos podem incluir: Sintomas ansiosos, como nervosismo, inquietação anormal, e dificuldade de se concentrar devido a preocupações. Sintomas melancólicos, que incluem desprazer ao realizar as atividades, falta de reatividade a estímulos, “humor vazio”, agitação, culpa excessiva e características anoréxicas. Sintomas atípicos, que contam com reatividade do humor,  aumento do apetite, hipersonia, paralisia “de chumbo” e sensibilidade à rejeição interpessoal. Um episódio depressivo maior pode causar um humor elevado, autoestima inflada, fuga de ideias, pensamentos acelerados, aumento na energia, redução da necessidade de sono.',
        links: []
    },
    {
        titulo: 'Transtornos de Ansiedade',
        texto: 'Os transtornos de ansiedade possuem características de medo e ansiedade excessivos: o medo é uma resposta emocional a uma ameaça iminente real ou percebida, já a ansiedade é a resposta diante de uma ameaça futura. Nos transtornos de ansiedade, os ataques de pânico se manifestam como uma resposta ao medo, porém não se limitam a esse tipo de transtorno; muitas vezes podem se desenvolver na infância e persistir até a vida adulta, se não tratados. Além disso, a maioria dos casos se manifesta em indivíduos do sexo feminino. Os traços ansiosos de um indivíduo são fortemente influenciados pela genética e estão sujeitos à interação gene-ambiente, ou seja, às influências ambientais. Existem diferentes transtornos ansiosos, dentre os quais estão: 1. Mutismo seletivo: extrema dificuldade para se expressar – principalmente pela fala – em situações sociais, como na escola. Esse tipo de transtorno afeta negativamente as experiências acadêmicas ou profissionais e interfere em outros aspectos da comunicação social. 2. Fobia social (transtorno de ansiedade social): caracterizado por manifestações ansiosas decorrentes de situações de possível avaliação, como encontro com pessoas que não são familiares, necessidade de comer ou beber em público ou desempenhar atividades em frente a outros. Isso é consequência do medo de avaliação negativa por outros indivíduos, de ser humilhado ou rejeitado. 3. Transtorno de pânico: incluem ataques de pânico decorrentes de situações de preocupação e apreensão, as características desses ataques incluem medo e desconfortos intensos, acompanhados de sintomas físicos e cognitivos. Algumas vezes, os ataques podem ocorrer sem uma razão aparente e não são limitados aos transtornos de ansiedade. 4. Transtorno de ansiedade generalizada: é marcado por ansiedade e preocupação persistentes decorrentes de vários âmbitos da vida (acadêmica, familiar, etc). Também incluem sintomas físicos, como inquietação, fatigabilidade, dificuldade de concentração, irritabilidade; tensão muscular; e perturbação do sono.',
        links: []
    },
    {
        titulo: 'Transtornos relacionados a substâncias e transtornos aditivos',
        texto: 'Os transtornos relacionados a substâncias incluem: álcool, cafeína, cannabis, alucinógenos, inalantes, opioides, sedativos, hipnóticos, ansiolíticos, estimulantes, tabaco e outras substâncias. O uso dessas substâncias causa sensações de prazer e atua na ativação do sistema de recompensa do cérebro, que envolve o reforço de comportamentos e na produção de memória. O uso constante pode induzir à tolerância, que é o estado em o SNC sofre adaptação e, então, faz-se necessário o uso de uma dose maior para gerar o efeito esperado. Esse grau de tolerância varia conforme o indivíduo e de uma substância para outra, os efeitos sobre o SNC também são variados. Os transtornos relacionados a substâncias podem ser por uso de substâncias ou induzidos por elas. O transtorno induzido por substância inclui intoxicação, abstinência e outros. Já o transtorno por uso de substância apresenta sintomas cognitivos, comportamentais e fisiológicos decorrentes do uso contínuo da droga; esse tipo de transtorno causa alteração básica nos circuitos cerebrais, que podem continuar mesmo após a desintoxicação. Alguns estudos apontam que pessoas com pouco autocontrole podem ser predispostas a desenvolver transtornos por uso de substâncias. Além disso, o sistema nervoso costuma ter uma resposta semelhante a outros padrões de comportamentos excessivos, como jogos online.',
        links: []
    },
    {
        titulo: 'Transtorno depressivo maior',
        texto: 'Critérios diagnóstico (sintomas presentes por um período de pelo menos duas semanas): humor deprimido ou irritável (no caso de crianças e adolescentes); perda do interesse ou prazer nas atividades; perda ou aumento significativo do peso sem estar em dieta; insônia ou hipersonia quase todos os dias; agitação ou retardo psicomotor; fadiga ou perda de energia; sentimentos de inutilidade ou culpa excessiva; capacidade diminuída para pensar ou se concentrar; pensamentos recorrentes de morte – como medo extremo de morrer ou pensamentos suicidas. Além disso, é comum o aumento da irritabilidade, como raiva persistente e tendência a responder a eventos com ataques de raiva. O transtorno depressivo maior possui maior probabilidade de se manifestar pela primeira vez na puberdade e os sintomas do transtorno geralmente causam prejuízo ao funcionamento social e profissional na vida do indivíduo. Para o diagnóstico, é necessário que a maioria dos sintomas estejam presentes em quase todos os dias do período depressivo, com exceção de alteração do peso e ideação suicida. Insônia, fadiga e perturbação costumam ser as principais queixas. Os pensamentos sobre morte incluem o desejo passivo de não acordar pela manhã, crença que as outras pessoas estariam melhores se o indivíduo estivesse morto e idealizações suicidas. A motivação para esses pensamentos pode ser “desejo de pôr fim a um estado emocional extremamente doloroso, incapacidade de antever algum prazer na vida ou o desejo de não ser uma carga para os outros” (APA, 2014). Quando os sintomas depressivos apresentam longa duração, as chances de desenvolver transtornos da personalidade, ansiedade e abuso de substância aumentam e a probabilidade de eficácia do tratamento diminui. De acordo com o Manual diagnóstico e estatístico de transtornos mentais (DSM-5): 1. “Depressões com início em idades mais precoces são mais familiares e mais prováveis de envolver transtornos da personalidade. [...] Experiências adversas na infância, particularmente quando existem múltiplas experiências de tipos diversos, constituem um conjunto de fatores de risco potenciais para transtorno depressivo maior. [...] Os familiares de primeiro grau de indivíduos com transtorno depressivo maior têm risco 2 a 4 vezes mais elevado de desenvolver a doença que a população em geral”.',
        links: []
    },
    {
        titulo: 'Gigiene do sono',
        texto: '“A higiene do sono é um conjunto de regras e práticas que devem ser seguidas ao ir dormir, com o objetivo de facilitar a chegada do sono, para que esse momento seja sempre relaxante e tranquilo. Além disso, a higiene do sono também busca trazer maior qualidade de sono, para que a pessoa acorde com a sensação de estar verdadeiramente descansada. Como esse é um importante processo fisiológico, essencial para o bem-estar do organismo, é necessário adotar medidas que sejam favoráveis e “amigas” do sono” (INSTITUTO DO SONO, 2022). Você pode ter acesso a informações complementares sobre essas temáticas acessando os seguintes tópicos, presentes no Interneurônios: “Comportamento”, “Emoção e motivação”, “Humores”, “Psicotrópicos”,  “Sono”, “Aprendizado e memória” e “Depressão”. Saiba mais sobre a higiene do sono (e como praticá-la) em:',
        links: ['https://institutodosono.com/artigos-noticias/higiene-do-sono-tudo-o-que-voce-precisa-saber-sobre-essa-pratica/', 'https://coral.ufsm.br/docsie/acolhimento/Higiene_do_sono.pdf', 'https://www.cnnbrasil.com.br/saude/higiene-do-sono-8-maneiras-de-treinar-seu-cerebro-para-dormir-melhor/']
    },
    {
        titulo: 'Temáticas do cotidiano',
        texto: 'Além das concepções biológicas da ansiedade, depressão e uso de drogas, existem análises nos âmbitos sociológicos, filosóficos de variadas áreas da saúde. Assim, a fim de ampliar o debate acerca dessas temáticas, está disponibilizado, abaixo, alguns vídeos que podem auxiliar em um debate sobre o assunto, dentro e fora da sala de aula.',
        links: ['https://youtu.be/vJNzJqXvg7s', 'https://youtu.be/pK2aLOYKSbs', 'https://youtu.be/iYvqb7P3n_g', 'https://youtu.be/8RgPyNiN6Dw', 'https://youtu.be/-jUBIUvvFYs', 'https://youtu.be/kwxyT5n6E9o', 'https://youtu.be/oaiwdnUPWxo', 'https://youtu.be/AU1rlvd6e9k', 'https://youtu.be/xKNDHtuIyTk', 'https://youtu.be/kXuDEB7HQ84', 'https://youtu.be/DSOMRi1HJeQ']
    },
    {
        titulo: 'Referência',
        texto: 'AMERICAN PSYCHIATRIC ASSOCIATION - APA. Manual diagnóstico e estatístico de transtornos mentais: DSM-5. Porto Alegre: Artmed, 2014.',
        links: []
    },
    {
        titulo: 'Referência',
        texto: 'BRITO, Isabel. Ansiedade e depressão na adolescência. Revista Portuguesa de Medicina Geral e Familiar, [S. l.], v. 27, n. 2, p. 208 - 214, 2011. DOI: 10.32385/rpmgf.v27i2.10842. Disponível em: https://rpmgf.pt/ojs/index.php/rpmgf/article/view/10842. Acesso em: 22 jul. 2023.',
        links: []
    },
    {
        titulo: 'Referência',
        texto: 'GROLLI, Verônica; WAGNER, Marcia Fortes; DALBOSCO, Simone Nenê Portela. Sintomas Depressivos e de Ansiedade em Adolescentes do Ensino Médio. Revista de Psicologia da Imed, [S.L.], v. 9, n. 1, p. 87-103, 14 nov. 2017. Complexo de Ensino Superior Meridional S.A.. http://dx.doi.org/10.18256/2175-5027.2017.v9i1.2123. Disponível em: https://dialnet.unirioja.es/servlet/articulo?codigo=6185316. Acesso em: 22 jul. 2023.'
    }

]

const sau_men = document.getElementById('saude_mental');

for (let saude of saude_mental) {
    sau_men.innerHTML +=
        `<div class="nome">${saude.titulo}</div>
        <div class="comando">${saude.texto}</div>
    `;

    for (let link of saude.links) {
        sau_men.innerHTML += `<p class="link">&#9679<a href="${link}"</a>${link}</p>`
    }
} 